### PR TITLE
Fix CortexIngesterRestarts alert

### PR DESCRIPTION
**Pull request by beorn7**

### CODE REVIEW

**Comment by gouthamve** [comment]
Okay, why will this not trigger on a rollout?

**Comment by beorn7** [comment]
It will trigger if you rollout more than once in 30m.

**Comment by beorn7** [comment]
You could do something like "more than 5 restarts in 1h" to be even less noisy, but let's see how we fare with the current threshold.

**Comment by pracucci** [comment]
_Thanks for fixing it! I should have noticed it during the review 🤦 _

**Pull request merged**
