### PR TITLE
Update mixin build instructions in README (fixes #223)

### LINKED ISSUE #223: RUNTIME ERROR: field does not exist: _config
When I want to generate the dashboards, I get an error:

`RUNTIME ERROR: field does not exist: _config`
        `dashboards.libsonnet:13:20-29   thunk <arr>`
        `std.jsonnet:225:20-23   thunk <v>`
        `std.jsonnet:32:25`
        `std.jsonnet:32:16-27    thunk <a>`
        `std.jsonnet:32:16-38    function <anonymous>`
        `std.jsonnet:32:16-38    function <anonymous>`
        `std.jsonnet:225:8-24    function <anonymous>`
        `dashboards.libsonnet:13:9-55    object <anonymous>`
        `During manifestation`

### PR DESCRIPTION
**Pull request by tomwilkie**
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

**What this PR does**:

Update mixin build instructions in README

**Which issue(s) this PR fixes**:
Fixes #223

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]` (not needed, just a readme update)

### CODE REVIEW

**Comment by RyanW8** [comment]
Just tried this but still can't get it to work. 
```
mkdir cortex-monitoring
GO111MODULE=on go get github.com/monitoring-mixins/mixtool/cmd/mixtool
GO111MODULE=on go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
```
However the directory is empty so theres no Makefile to build from. Are there any other steps that are missing?


I've also tried
```
ryan@WINDOWS-H8Q4C40:~$ git clone https://github.com/grafana/cortex-jsonnet.git
Cloning into 'cortex-jsonnet'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 2157 (delta 75), reused 69 (delta 38), pack-reused 2025
Receiving objects: 100% (2157/2157), 663.51 KiB | 1.96 MiB/s, done.
Resolving deltas: 100% (1464/1464), done.
ryan@WINDOWS-H8Q4C40:~$ cd cortex-jsonnet/
ryan@WINDOWS-H8Q4C40:~/cortex-jsonnet$ GO111MODULE=on go get github.com/monitoring-mixins/mixtool/cmd/mixtool
go: found github.com/monitoring-mixins/mixtool/cmd/mixtool in github.com/monitoring-mixins/mixtool v0.0.0-20201215163959-44fc090c10e7
ryan@WINDOWS-H8Q4C40:~/cortex-jsonnet$ GO111MODULE=on go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
go: found github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb in github.com/jsonnet-bundler/jsonnet-bundler v0.4.0
ryan@WINDOWS-H8Q4C40:~/cortex-jsonnet$ cd cortex-jsonnet/^C
ryan@WINDOWS-H8Q4C40:~/cortex-jsonnet$ make build-mixin
cd cortex-mixin && \
rm -rf out && mkdir out && \
jb install && \
mixtool generate all --output-alerts out/alerts.yaml --output-rules out/rules.yaml --directory out/dashboards mixin.libsonnet && \
zip -r cortex-mixin.zip out
GET https://github.com/grafana/jsonnet-libs/archive/8f9d72b2e35b5f3cc1b7c2a8af9bbae7658804e2.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/21b638f4e4922c0b6fde12120ed45d8ef803edc7.tar.gz 200
/bin/sh: 4: mixtool: not found
Makefile:29: recipe for target 'build-mixin' failed
make: *** [build-mixin] Error 127
```

**Comment by tomwilkie** [comment]
(Discuss on slack with Ryan, $GOPATH/bin wasn't in his $PATH)

**Comment by RyanW8** [comment]
I've also just found that this generates config assuming each of the Cortex components has a Prometheus job with the same name. I.e `job="($namespace)/ruler"`. Can we get this added to the documentation too? We're currently using Prometheus `kubernetes_sd_config`. That way we don't have to update the targets as it'll stay in sync as the cluster grows. Maybe might be worth sharing how you guys do it with the different jobs per component

**Comment by tomwilkie** [comment]
> I've also just found that this generates config assuming each of the Cortex components has a Prometheus job with the same name. I.e job="($namespace)/ruler"

There is a config option to enable "single binary mode" - see https://github.com/grafana/cortex-jsonnet/blob/master/cortex-mixin/config.libsonnet#L24

> Can we get this added to the documentation too?

Can you file an issue / open a ticket for this please?

> We're currently using Prometheus kubernetes_sd_config. That way we don't have to update the targets as it'll stay in sync as the cluster grows. Maybe might be worth sharing how you guys do it with the different jobs per component

We do to; the relabelling rule we use to add the namespace to the job names is here: https://github.com/grafana/jsonnet-libs/blob/master/prometheus-ksonnet/lib/prometheus-config.libsonnet#L128

**Review by pstibrany — APPROVED** [review]

**Pull request merged**
